### ISSUE TITLE
Please attatch the video link

### ISSUE THREAD

**Issue by LaiPiXiong** [CreatCodeBuild/TensorFlow-Chinese-Tutorial#30]
Hi, I have watched your video tutorial for times, I really learn a lots. Does this section video tutorial has accomplished? For 'Bilibili' returns only the session one when i search 'TF-Grirls'. Can you please attach your video link? that's will be really thankful.

**Comment by cs690creativedev** [comment]
[https://space.bilibili.com/16696495#!/channel/detail?cid=1588](url)

**Comment by LaiPiXiong** [comment]
It cannot open, shows 404 error.
