### ISSUE TITLE
该从何入手呢？

### ISSUE THREAD

**Issue by wilddylan** [CreatCodeBuild/TensorFlow-Chinese-Tutorial#9]
该从何入手呢？需要一些什么只是储备呢？ Thx

**Comment by isaced** [comment]
第一节就讲了需要什么知识储备。

<img width="584" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2088605/21125536/6f0a8dba-c121-11e6-8070-3f19f91a818f.png">

**Comment by wilddylan** [comment]
我先去看看这些基础。首次接触机器学习
